---
- hosts: all
  tags: all
  become: true
  pre_tasks:
    - name: pre-run | update package cache (Debian based)
      tags: always
      apt: update_cache=yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

# run roles
- hosts: all
  tags: all
  become: true
  roles:
    - base

