
- block:

  ## desktop environments
  
  - include_tasks: desktop_environments/gnome/packages.yml
    #when: gnome is defined and gnome == true

  ## system setup:
  
  - import_tasks: system_setup/utilities.yml

  ## install software
  
  - import_tasks: software/bitwarden.yml
  - import_tasks: software/firefox.yml
